name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 12 * * 0,3,5'
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase REST API
        run: |
          curl -X GET "${{ secrets.MI_SUPABASE_URL }}/rest/v1/" \
            -H "apikey: ${{ secrets.MI_SUPA_AUTO }}" \
            -H "Authorization: Bearer ${{ secrets.MI_SUPA_AUTO }}"
