name: Supabase Ping

on:
  schedule:
    - cron: '0 12 * * 0,3,5'
  workflow_dispatch:

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Request REST API
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
